version: "3"

services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/app
    depends_on:
      - fpm
    ports:
      - "8080:80"
    networks:
      - backend

  fpm:
    build:
      context: ./.docker
      dockerfile: fpm.dockerfile
    volumes:
      - ./:/app
    networks:
      - backend
    depends_on:
      - postgres
    environment:
      XDEBUG_IDE_KEY: "PHPSTORM"
      XDEBUG_REMOTE_HOST: "192.166.220.1"
      PHP_IDE_CONFIG: "serverName=Docker"

  cli:
    build:
      context: ./.docker
      dockerfile: cli.dockerfile
    volumes:
      - ./:/app
    networks:
      - backend
    depends_on:
      - postgres
    tty: true

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.166.220.0/16

volumes:
  postgres-data:
