version: "3"

services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
    volumes:
      - ./:/app
    depends_on:
      - fpm
    ports:
      - "8080:80"
    networks:
      - backend

  fpm:
#    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    build:
      context: ./.docker
      dockerfile: fpm.dockerfile
    volumes:
      - ./:/app
    networks:
      - backend
    depends_on:
      - postgres
    environment:
      XDEBUG_CONFIG: "remote_host=192.166.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"

  cli:
#    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    build:
      context: ./.docker
      dockerfile: cli.dockerfile
    volumes:
      - ./:/app
    networks:
      - backend
    depends_on:
      - postgres
    tty: true

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: forge
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.166.220.0/16
